version: '3.3'

services:

  site:
    build:
      context: ./
      dockerfile: ./site/Dockerfile

  subsite:
    build:
      context: ./
      dockerfile: ./subsite/Dockerfile

  proxy:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile